_linux_env: &linux_env
  env:
  - 'PYTHON_LIBS="-L$(python-config --prefix)/lib $(python-config --libs)"'
  - PY_ENABLE_SHARD=0
  - MULTI_PROCESS_PARAMS="--processes=-1 --process-timeout=180"

sudo: required
language: python

matrix:
  include:
    - os: linux
      python: 3.6
      <<: *linux_env
    - os: linux
      python: 3.7
      <<: *linux_env
    - os: linux
      python: 3.8
      dist: bionic
      sudo: required
      <<: *linux_env
    - os: osx
      language: generic
      env: PY_VERSION=3.6.10
    - os: osx
      language: generic
      env: PY_VERSION=3.7.6
    - os: osx
      language: generic
      env: PY_VERSION=3.8.1

addons:
  # This is used for SFTP integration tests
  ssh_known_hosts: ec2-18-209-45-78.compute-1.amazonaws.com

before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PY_VERSION
    export PYENV_VERSION=$PY_VERSION
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    pip install nose mock
  fi

install:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update
    sudo apt-get install gnome-keyring
  fi
- pip install -U setuptools
- travis_wait pip install pysftp pandas boto3
- python setup.py install

before_script:
- | # decrypt credentials used in tests
  if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_d17283647768_key -iv $encrypted_d17283647768_iv -in test.synapseConfig.enc -out test.synapseConfig -d
    mv test.synapseConfig ~/.synapseConfig
  fi


script:
- nosetests --traverse-namespace -s tests/unit
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ];then
    nosetests $MULTI_PROCESS_PARAMS --traverse-namespace -s -v tests/integration
  else
    echo "Skipping integration tests";
  fi
