sudo: false
language: python

script:
- python setup.py install
- nosetests -vs tests/unit
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then nosetests -vs tests/integration; else echo "Skipping integration tests"; fi'

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PY_VERSION
    export PYENV_VERSION=$PY_VERSION
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    pip install nose mock
  fi
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    apt-get install gnome-keyring
    apt-get install libdbus-glib-1-dev
    pip install dbus-python
  fi


  if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_d17283647768_key -iv $encrypted_d17283647768_iv -in test.synapseConfig.enc -out test.synapseConfig -d
    mv test.synapseConfig ~/.synapseConfig
    openssl aes-256-cbc -K $encrypted_d17283647768_key -iv $encrypted_d17283647768_iv -in test.awscredentials.enc -out test.awscredentials -d
    mkdir -p ~/.aws && mv test.awscredentials ~/.aws/credentials
  fi
  travis_wait pip install pysftp cython pandas boto3

addons:
  ssh_known_hosts: ec2-54-212-85-156.us-west-2.compute.amazonaws.com

matrix:
  include:
    - os: linux
      python: 2.7.14
    - os: linux
      python: 3.5.3
    - os: linux
      python: 3.6.2
    - os: osx
      language: generic
      env: PY_VERSION=2.7.14
    - os: osx
      language: generic
      env: PY_VERSION=3.5.3
    - os: osx
      language: generic
      env: PY_VERSION=3.6.2